// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: tweet.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createNewTweet = `-- name: CreateNewTweet :one
insert into tweets (id, content, media, public_id, user_id) values ($1, $2, $3, $4, $5) returning id, content, media, public_id, user_id, reply_tweet_id, repost
`

type CreateNewTweetParams struct {
	ID       uuid.UUID
	Content  sql.NullString
	Media    sql.NullString
	PublicID sql.NullString
	UserID   uuid.UUID
}

func (q *Queries) CreateNewTweet(ctx context.Context, arg CreateNewTweetParams) (Tweet, error) {
	row := q.db.QueryRowContext(ctx, createNewTweet,
		arg.ID,
		arg.Content,
		arg.Media,
		arg.PublicID,
		arg.UserID,
	)
	var i Tweet
	err := row.Scan(
		&i.ID,
		&i.Content,
		&i.Media,
		&i.PublicID,
		&i.UserID,
		&i.ReplyTweetID,
		&i.Repost,
	)
	return i, err
}

const deleteATweet = `-- name: DeleteATweet :one
delete from tweets where id=$1 and user_id=$2 returning id, content, media, public_id, user_id, reply_tweet_id, repost
`

type DeleteATweetParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) DeleteATweet(ctx context.Context, arg DeleteATweetParams) (Tweet, error) {
	row := q.db.QueryRowContext(ctx, deleteATweet, arg.ID, arg.UserID)
	var i Tweet
	err := row.Scan(
		&i.ID,
		&i.Content,
		&i.Media,
		&i.PublicID,
		&i.UserID,
		&i.ReplyTweetID,
		&i.Repost,
	)
	return i, err
}

const findATweet = `-- name: FindATweet :one
select id, content, media, public_id, user_id, reply_tweet_id, repost from tweets where id=$1
`

func (q *Queries) FindATweet(ctx context.Context, id uuid.UUID) (Tweet, error) {
	row := q.db.QueryRowContext(ctx, findATweet, id)
	var i Tweet
	err := row.Scan(
		&i.ID,
		&i.Content,
		&i.Media,
		&i.PublicID,
		&i.UserID,
		&i.ReplyTweetID,
		&i.Repost,
	)
	return i, err
}
