// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: user.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one
insert into users (id, username, password, email, created_at, updated_at) values ($1, $2, $3, $4, $5, $6) returning id, username, password, refresh_token, email, created_at, updated_at
`

type CreateUserParams struct {
	ID        uuid.UUID
	Username  string
	Password  string
	Email     string
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.ID,
		arg.Username,
		arg.Password,
		arg.Email,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Password,
		&i.RefreshToken,
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUniqueUser = `-- name: GetUniqueUser :one
select count(*) from users where username=$1 or email=$2
`

type GetUniqueUserParams struct {
	Username string
	Email    string
}

func (q *Queries) GetUniqueUser(ctx context.Context, arg GetUniqueUserParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, getUniqueUser, arg.Username, arg.Email)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getUserById = `-- name: GetUserById :one
select id, username, password, refresh_token, email, created_at, updated_at from users where id=$1
`

func (q *Queries) GetUserById(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserById, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Password,
		&i.RefreshToken,
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByName = `-- name: GetUserByName :one
select id, username, password, refresh_token, email, created_at, updated_at from users where username=$1
`

func (q *Queries) GetUserByName(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByName, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Password,
		&i.RefreshToken,
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updatePassword = `-- name: UpdatePassword :one
update users set password=$1,updated_at=$2 where id=$3 returning id, username, password, refresh_token, email, created_at, updated_at
`

type UpdatePasswordParams struct {
	Password  string
	UpdatedAt time.Time
	ID        uuid.UUID
}

func (q *Queries) UpdatePassword(ctx context.Context, arg UpdatePasswordParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updatePassword, arg.Password, arg.UpdatedAt, arg.ID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Password,
		&i.RefreshToken,
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateRefreshToken = `-- name: UpdateRefreshToken :one
update users set refresh_token=$1, updated_at=$2 where id=$3 returning id, username, password, refresh_token, email, created_at, updated_at
`

type UpdateRefreshTokenParams struct {
	RefreshToken sql.NullString
	UpdatedAt    time.Time
	ID           uuid.UUID
}

func (q *Queries) UpdateRefreshToken(ctx context.Context, arg UpdateRefreshTokenParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateRefreshToken, arg.RefreshToken, arg.UpdatedAt, arg.ID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Password,
		&i.RefreshToken,
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
