// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Follow struct {
	ID        uuid.UUID
	Follower  uuid.UUID
	Following uuid.UUID
}

type Like struct {
	ID      uuid.UUID
	UserID  uuid.UUID
	TweetID uuid.UUID
}

type LikesCount struct {
	TweetID uuid.UUID
	Count   sql.NullInt32
}

type Repost struct {
	ID      uuid.UUID
	UserID  uuid.UUID
	TweetID uuid.UUID
}

type RepostCount struct {
	TweetID uuid.UUID
	Count   int32
}

type Tweet struct {
	ID           uuid.UUID
	Content      sql.NullString
	Media        sql.NullString
	PublicID     sql.NullString
	CreatedAt    time.Time
	UserID       uuid.UUID
	ReplyTweetID uuid.NullUUID
	Repost       uuid.NullUUID
}

type User struct {
	ID           uuid.UUID
	Username     string
	Password     string
	RefreshToken sql.NullString
	Email        string
	CreatedAt    time.Time
	UpdatedAt    time.Time
}
